"""More Table Added

Revision ID: d875767fd153
Revises: 7f9288ebcde3
Create Date: 2026-07-30 01:12:33.884139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd875767fd153'
down_revision: Union[str, Sequence[str], None] = '7f9288ebcde3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correlation_rules',
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('rule_type', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('parameters_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('auto_escalate_threshold', sa.Integer(), nullable=False),
    sa.Column('auto_escalate_severity', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_correlation_rules_org_active', 'correlation_rules', ['organization_id', 'is_active'], unique=False)
    op.create_table('correlation_clusters',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('center_latitude', sa.Float(), nullable=True),
    sa.Column('center_longitude', sa.Float(), nullable=True),
    sa.Column('alert_count', sa.Integer(), nullable=False),
    sa.Column('max_severity', sa.String(length=20), nullable=False),
    sa.Column('escalated_incident_id', sa.UUID(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['escalated_incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['correlation_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_correlation_clusters_org_status', 'correlation_clusters', ['organization_id', 'status'], unique=False)
    op.create_table('correlation_cluster_members',
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cluster_id'], ['correlation_clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_correlation_member_unique', 'correlation_cluster_members', ['cluster_id', 'alert_id'], unique=True)
    op.alter_column('incident_updates', 'author_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('incident_updates_author_id_fkey'), 'incident_updates', type_='foreignkey')
    op.create_foreign_key(None, 'incident_updates', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.add_column('incidents', sa.Column('is_system_generated', sa.Boolean(), nullable=False))
    op.alter_column('incidents', 'created_by_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('incidents_created_by_id_fkey'), 'incidents', type_='foreignkey')
    op.create_foreign_key(None, 'incidents', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.create_foreign_key(op.f('incidents_created_by_id_fkey'), 'incidents', 'users', ['created_by_id'], ['id'], ondelete='CASCADE')
    op.alter_column('incidents', 'created_by_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('incidents', 'is_system_generated')
    op.drop_constraint(None, 'incident_updates', type_='foreignkey')
    op.create_foreign_key(op.f('incident_updates_author_id_fkey'), 'incident_updates', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.alter_column('incident_updates', 'author_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('ix_correlation_member_unique', table_name='correlation_cluster_members')
    op.drop_table('correlation_cluster_members')
    op.drop_index('ix_correlation_clusters_org_status', table_name='correlation_clusters')
    op.drop_table('correlation_clusters')
    op.drop_index('ix_correlation_rules_org_active', table_name='correlation_rules')
    op.drop_table('correlation_rules')
    # ### end Alembic commands ###
