"""Added Risk Assessment

Revision ID: f2d80cb5b13f
Revises: d875767fd153
Create Date: 2026-07-31 22:00:27.087270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2d80cb5b13f'
down_revision: Union[str, Sequence[str], None] = 'd875767fd153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_profiles',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('monitored_radius_km', sa.Float(), nullable=True),
    sa.Column('monitored_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weighting_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_profiles_org', 'risk_profiles', ['organization_id', 'is_active'], unique=False)
    op.create_table('risk_scores',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('factor_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['risk_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_scores_profile_calculated', 'risk_scores', ['profile_id', 'calculated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_risk_scores_profile_calculated', table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index('ix_risk_profiles_org', table_name='risk_profiles')
    op.drop_table('risk_profiles')
    # ### end Alembic commands ###
